name: Android APK Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Validate repository
        run: |
          echo "Listing repository files for debug"
          ls -la
          test -f package.json || (echo "package.json not found" && exit 2)

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Upload unit test logs
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-logs
          path: |
            test-results || true
          retention-days: 7

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: unit-tests
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        # Run `npm run e2e` if script present; keep this step tolerant if no e2e script is defined.
        run: npm run e2e --if-present || echo "No e2e script defined; skipping"

  web-build:
    name: Web build
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist/
          retention-days: 7

  gradle-build:
    runs-on: ubuntu-latest
    needs: web-build
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK command-line tools and platforms (CI)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip wget
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline.zip
          unzip -q /tmp/cmdline.zip -d $HOME/android-sdk/cmdline-tools
          # move into expected path
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ || true
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          # Accept licenses and install essential packages
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses || true
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          ls -la $ANDROID_SDK_ROOT
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk


      - name: Install Node.js dependencies (for Capacitor Android)
        run: npm ci

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Release APK (assembleRelease)
        run: |
          set -eux
          # Ensure we're using the android gradle wrapper
          cd android
          chmod +x ./gradlew || true
          echo "Using java: $(java -version 2>&1 | head -n 1)"
          echo "Gradle wrapper:" && ls -la ./gradlew
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 30

  release:
    needs: gradle-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
